### ISSUE TITLE
failed to execute scripts due to missing files

### ISSUE THREAD

**Issue by hyy9810** [canchang00/e_mapp#1]
```bash scripts/train_sast.sh``` -> FileNotFoundError: [Errno 2] No such file or directory: 'levels/sast/random1501_program.txt'
``` bash scripts/train_perception.sh``` -> FileNotFoundError: [Errno 2] No such file or directory: 'levels/perception/random834_program.txt'
``` bash scripts/train_reach.sh``` -> FileNotFoundError: [Errno 2] No such file or directory: 'levels/mast/random1501_program.txt'
``` bash scripts/train_cooperation.sh``` -> FileNotFoundError: [Errno 2] No such file or directory: 'levels/mast-cooperation/random0_program.txt'
``` bash scripts/train_feas.sh```  -> FileNotFoundError: [Errno 2] No such file or directory: 'levels/mast-chaos/random0_program.txt'
``` bash scripts/evaluate.sh``` -> FileNotFoundError: No file 'misc/game/graphics/TomatoSupply.png' found in working directory.

**Comment by canchang00** [comment]
Hi. You should use the file ```scene_generation.py``` to generate scenes and their guiding programs. After that you can will get the files you want. We provide example programs in the ```program``` directory, but you can write your own programs following the DSL.

**Comment by hyy9810** [comment]
> Hi. You should use the file `scene_generation.py` to generate scenes and their guiding programs. After that you can will get the files you want. We provide example programs in the `program` directory, but you can write your own programs following the DSL.

Additionally the pictures in ```misc/game/graphics``` seems to be missing, including ```delivery.png```, ```Dirtyplate.png``` and other 10 pictures.

**Comment by canchang00** [comment]
Thank you for bringing the issue to my attention. I have uploaded the missing pictures.
